### ISSUE TITLE
The option "default" does not exist. Defined options are: "host", "linger", "persistent", "port", "protocol". 

### ISSUE THREAD

**Issue by thioky** [GeniusesOfSymfony/WebSocketBundle#388]
My config.
config/packages/gos_web_socket.yaml on Symfony 4

gos_web_socket:
    shared_config: true
    server:
        host: 127.0.0.1   #The host ip to bind to
        port: 8001        #The port the socket server will listen on
        router:
            resources:
                - '%kernel.project_dir%/config/pubsub/routing.yaml'

    client:
        firewall: main
        session_handler: session.handler.pdo
        storage:
            driver: '@gos_web_socket.server.in_memory.client_storage.driver'
            ttl: 28800
            prefix:  'client'
            decorator: ~

    pushers:
        zmq:
            default: true
            host: 127.0.0.1
            port: 5555
            persistent: true
            protocol: tcp

**Comment by mbabker** [comment]
Fixed.  That "default" config node might go away in the future, I just did a scan and it's not actually used anywhere.

**Comment by thioky** [comment]
Hello,
I removed the default part but still have the same error.

pushers:
        ZMQ:
            host: 127.0.0.1
            port: 8001
            persist: true
            protocol: tcp

What should i put in services.yaml in this case.

**Comment by thioky** [comment]
What configuration should i do then to use $pusher = $this->container->get('gos_web_socket.zmq.pusher'); in my controller

**Comment by mbabker** [comment]
Did you do a `composer update`?

Also, make sure you set the pusher as enabled (required with the 2.0 branch, which it seems you're using if you've gotten the error you listed).  This should be the minimum YAML you need to make the ZMQ pusher work (the rest will use defaults if you don't set anything else), but I can't say with any certainty it actually will work (I'm not using the ZMQ pusher myself and haven't yet finished setting up a test environment to add tests for that to the bundle).

```yaml
gos_web_socket:
    pushers:
        zmq:
            enabled: true
            host: 127.0.0.1
            port: 5555
```
